baseURL = "https://biniter1.github.io/my-blog/"
languageCode = "vi-vn"
title = "Blog cá nhân của Sonbin"
theme = "PaperMod"

[params]
# Cấu hình cho theme PaperMod
defaultTheme = "auto" # "light", "dark" hoặc "auto"
ShowShareButtons = true
ShowReadingTime = true
ShowPostNavLinks = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Bài viết"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "Giới thiệu"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier= "projects"
    name =" Personal Project"
    url= "/projects/"
    weight=25
  [[menu.main]]
    identifier = "tags"
    name = "Thẻ"
    url = "/tags/"
    weight = 30
